<!ENTITY % settings SYSTEM "settings.xml.inc">
%settings;

<!ENTITY datasource-settings SYSTEM "datasource-settings.xml.inc">
<!ENTITY fontset-settings SYSTEM "fontset-settings.xml.inc">

<!ENTITY % otm-font-settings SYSTEM "otm-font-settings.xml.inc">
%otm-font-settings;

<!ENTITY % otm-zoom-settings SYSTEM "otm-zoom-settings.xml.inc">
%otm-zoom-settings;

<!ENTITY % otm-tracks-settings SYSTEM "otm-tracks-settings.xml.inc">
%otm-tracks-settings;

<!ENTITY % otm-contours-colors-standard SYSTEM "otm-contours-colors-standard.xml.inc">
%otm-contours-colors-standard;

<!ENTITY otm-tracks-layers SYSTEM "otm-tracks-layers.xml.inc">
<!ENTITY otm-tracks-styles SYSTEM "otm-tracks-styles.xml.inc">
<!ENTITY otm-tracks-debug-layers SYSTEM "otm-tracks-debug-layers.xml.inc">
<!ENTITY otm-tracks-debug-styles SYSTEM "otm-tracks-debug-styles.xml.inc">
<!ENTITY otm-hillshade-layers SYSTEM "otm-hillshade-layers.xml.inc">
<!ENTITY otm-hillshade-styles SYSTEM "otm-hillshade-styles.xml.inc">
<!ENTITY otm-contours-layers SYSTEM "otm-contours-layers.xml.inc">
<!ENTITY otm-contours-styles SYSTEM "otm-contours-styles.xml.inc">



<!ENTITY srs900913 "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs +over">
<!ENTITY srsmercator "+proj=merc +datum=WGS84 +over">
<!ENTITY srs4326 "+init=epsg:4326">

<!ENTITY % layers SYSTEM "layers.xml.inc">
%layers;

