<!ENTITY % settings SYSTEM "settings.xml.inc">
%settings;
<!ENTITY datasource-settings SYSTEM "datasource-settings.xml.inc">
<!ENTITY latlon-datasource-settings SYSTEM "latlon-datasource-settings.xml.inc">
<!ENTITY fontset-settings SYSTEM "fontset-settings.xml.inc">
<!ENTITY % font-settings SYSTEM "font-settings.xml.inc">
%font-settings;
<!ENTITY % zoom-settings SYSTEM "zoom-settings.xml.inc">
%zoom-settings;
<!ENTITY % tracks-settings SYSTEM "tracks-settings.xml.inc">
%tracks-settings;
<!ENTITY tracks-layers SYSTEM "tracks-layers.xml.inc">
<!ENTITY tracks-styles SYSTEM "tracks-styles.xml.inc">
<!ENTITY tracks-debug-layers SYSTEM "tracks-debug-layers.xml.inc">
<!ENTITY tracks-debug-styles SYSTEM "tracks-debug-styles.xml.inc">
<!ENTITY hillshade-layers SYSTEM "hillshade-layers.xml.inc">
<!ENTITY hillshade-styles SYSTEM "hillshade-styles.xml.inc">
<!ENTITY contours-layers SYSTEM "contours-layers.xml.inc">
<!ENTITY contours-styles SYSTEM "contours-styles.xml.inc">
<!ENTITY srs900913 "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs +over">
<!ENTITY srsmercator "+proj=merc +datum=WGS84 +over">
//?
