<!ENTITY yellow "<CssParameter name='stroke'>#dddd00</CssParameter>">
<!ENTITY red "<CssParameter name='stroke'>#dd0000</CssParameter>">
<!ENTITY green "<CssParameter name='stroke'>#00dd00</CssParameter>">
<!ENTITY blue "<CssParameter name='stroke'>#0000dd</CssParameter>">
<!ENTITY one_track_small "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                          <CssParameter name='stroke-width'>1</CssParameter>">
<!ENTITY one_track_normal "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                           <CssParameter name='stroke-width'>2</CssParameter>">
<!ENTITY one_track_big "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                        <CssParameter name='stroke-width'>3</CssParameter>">
<!ENTITY one_track_huge "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                         <CssParameter name='stroke-width'>4</CssParameter>">
<!ENTITY two_tracks_small_1 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                             <CssParameter name='stroke-width'>1</CssParameter>
                             <CssParameter name='stroke-dasharray'>2,2</CssParameter>">
<!ENTITY two_tracks_small_2 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                             <CssParameter name='stroke-width'>1</CssParameter>
                             <CssParameter name='stroke-dasharray'>0,2,2,0</CssParameter>">
<!ENTITY two_tracks_normal_1 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                              <CssParameter name='stroke-width'>2</CssParameter>
                              <CssParameter name='stroke-dasharray'>4,4</CssParameter>">
<!ENTITY two_tracks_normal_2 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                              <CssParameter name='stroke-width'>2</CssParameter>
                              <CssParameter name='stroke-dasharray'>0,4,4,0</CssParameter>">
<!ENTITY two_tracks_big_1 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                           <CssParameter name='stroke-width'>3</CssParameter>
                           <CssParameter name='stroke-dasharray'>6,6</CssParameter>">
<!ENTITY two_tracks_big_2 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                           <CssParameter name='stroke-width'>3</CssParameter>
                           <CssParameter name='stroke-dasharray'>0,6,6,0</CssParameter>">
<!ENTITY two_tracks_huge_1 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                            <CssParameter name='stroke-width'>4</CssParameter>
                            <CssParameter name='stroke-dasharray'>8,8</CssParameter>">
<!ENTITY two_tracks_huge_2 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                            <CssParameter name='stroke-width'>4</CssParameter>
                            <CssParameter name='stroke-dasharray'>0,8,8,0</CssParameter>">
<!ENTITY three_tracks_small_1 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                               <CssParameter name='stroke-width'>1</CssParameter>
                               <CssParameter name='stroke-dasharray'>2,4</CssParameter>">
<!ENTITY three_tracks_small_2 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                               <CssParameter name='stroke-width'>1</CssParameter>
                               <CssParameter name='stroke-dasharray'>0,2,2,2</CssParameter>">
<!ENTITY three_tracks_small_3 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                               <CssParameter name='stroke-width'>1</CssParameter>
                               <CssParameter name='stroke-dasharray'>0,4,2,0</CssParameter>">
<!ENTITY three_tracks_normal_1 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                                <CssParameter name='stroke-width'>2</CssParameter>
                                <CssParameter name='stroke-dasharray'>4,8</CssParameter>">
<!ENTITY three_tracks_normal_2 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                                <CssParameter name='stroke-width'>2</CssParameter>
                                <CssParameter name='stroke-dasharray'>0,4,4,4</CssParameter>">
<!ENTITY three_tracks_normal_3 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                                <CssParameter name='stroke-width'>2</CssParameter>
                                <CssParameter name='stroke-dasharray'>0,8,4,0</CssParameter>">
<!ENTITY three_tracks_big_1 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                             <CssParameter name='stroke-width'>3</CssParameter>
                             <CssParameter name='stroke-dasharray'>6,12</CssParameter>">
<!ENTITY three_tracks_big_2 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                             <CssParameter name='stroke-width'>3</CssParameter>
                             <CssParameter name='stroke-dasharray'>0,6,6,6</CssParameter>">
<!ENTITY three_tracks_big_3 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                             <CssParameter name='stroke-width'>3</CssParameter>
                             <CssParameter name='stroke-dasharray'>0,12,6,0</CssParameter>">
<!ENTITY three_tracks_huge_1 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                              <CssParameter name='stroke-width'>4</CssParameter>
                              <CssParameter name='stroke-dasharray'>8,16</CssParameter>">
<!ENTITY three_tracks_huge_2 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                              <CssParameter name='stroke-width'>4</CssParameter>
                              <CssParameter name='stroke-dasharray'>0,8,8,8</CssParameter>">
<!ENTITY three_tracks_huge_3 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                              <CssParameter name='stroke-width'>4</CssParameter>
                              <CssParameter name='stroke-dasharray'>0,16,8,0</CssParameter>">
<!ENTITY four_tracks_small_1 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                              <CssParameter name='stroke-width'>1</CssParameter>
                              <CssParameter name='stroke-dasharray'>2,6</CssParameter>">
<!ENTITY four_tracks_small_2 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                              <CssParameter name='stroke-width'>1</CssParameter>
                              <CssParameter name='stroke-dasharray'>0,2,2,4</CssParameter>">
<!ENTITY four_tracks_small_3 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                              <CssParameter name='stroke-width'>1</CssParameter>
                              <CssParameter name='stroke-dasharray'>0,4,2,2</CssParameter>">
<!ENTITY four_tracks_small_4 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                              <CssParameter name='stroke-width'>1</CssParameter>
                              <CssParameter name='stroke-dasharray'>0,6,2,0</CssParameter>">
<!ENTITY four_tracks_normal_1 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                             <CssParameter name='stroke-width'>1</CssParameter>
                             <CssParameter name='stroke-dasharray'>4,12</CssParameter>">
<!ENTITY four_tracks_normal_2 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                               <CssParameter name='stroke-width'>2</CssParameter>
                               <CssParameter name='stroke-dasharray'>0,4,4,8</CssParameter>">
<!ENTITY four_tracks_normal_3 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                               <CssParameter name='stroke-width'>2</CssParameter>
                               <CssParameter name='stroke-dasharray'>0,8,4,4</CssParameter>">
<!ENTITY four_tracks_normal_4 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                               <CssParameter name='stroke-width'>2</CssParameter>
                               <CssParameter name='stroke-dasharray'>0,12,4,0</CssParameter>">
<!ENTITY four_tracks_big_1 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                             <CssParameter name='stroke-width'>3</CssParameter>
                             <CssParameter name='stroke-dasharray'>6,18</CssParameter>">
<!ENTITY four_tracks_big_2 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                             <CssParameter name='stroke-width'>3</CssParameter>
                             <CssParameter name='stroke-dasharray'>0,6,6,12</CssParameter>">
<!ENTITY four_tracks_big_3 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                             <CssParameter name='stroke-width'>3</CssParameter>
                             <CssParameter name='stroke-dasharray'>0,12,6,6</CssParameter>">
<!ENTITY four_tracks_big_4 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                             <CssParameter name='stroke-width'>3</CssParameter>
                             <CssParameter name='stroke-dasharray'>0,18,6,0</CssParameter>">
<!ENTITY four_tracks_huge_1 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                             <CssParameter name='stroke-width'>4</CssParameter>
                             <CssParameter name='stroke-dasharray'>8,24</CssParameter>">
<!ENTITY four_tracks_huge_2 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                             <CssParameter name='stroke-width'>4</CssParameter>
                             <CssParameter name='stroke-dasharray'>0,8,8,16</CssParameter>">
<!ENTITY four_tracks_huge_3 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                             <CssParameter name='stroke-width'>4</CssParameter>
                             <CssParameter name='stroke-dasharray'>0,16,8,8</CssParameter>">
<!ENTITY four_tracks_huge_4 "<CssParameter name='stroke-opacity'>1.0</CssParameter>
                             <CssParameter name='stroke-width'>4</CssParameter>
                             <CssParameter name='stroke-dasharray'>0,24,8,0</CssParameter>">
<!--
<!ENTITY % yellow_track "(not [kct_yellow].match('^$|^bicycle$') or not [marked_trail_yellow].match('^$|^bicycle$') or [marked_trail].match('^yellow.*$'))">
<!ENTITY % red_track "(not [kct_red].match('^$|^bicycle$') or not [marked_trail_red].match('^$|^bicycle$') or [marked_trail].match('^red.*$'))">
<!ENTITY % green_track "(not [kct_green].match('^$|^bicycle$') or not [marked_trail_green].match('^$|^bicycle$') or [marked_trail].match('^green.*$'))">
<!ENTITY % blue_track "(not [kct_blue].match('^$|^bicycle$') or not [marked_trail_blue].match('^$|^bicycle$') or [marked_trail].match('^blue.*$'))">
-->
<!ENTITY % yellow_track "(not [kct_yellow].match('^$|^kokotov$'))">
<!ENTITY % red_track "(not [kct_red].match('^$|^kokotov$'))">
<!ENTITY % green_track "(not [kct_green].match('^$|^kokotov$'))">
<!ENTITY % blue_track "(not [kct_blue].match('^$|^kokotov$'))">

<!ENTITY yellow_hiking_filter "<Filter>%yellow_track; and not %red_track; and not %green_track; and not %blue_track;</Filter>">
<!ENTITY red_hiking_filter "<Filter>not %yellow_track; and %red_track; and not %green_track; and not %blue_track;</Filter>">
<!ENTITY green_hiking_filter "<Filter>not %yellow_track; and not %red_track; and %green_track; and not %blue_track;</Filter>">
<!ENTITY blue_hiking_filter "<Filter>not %yellow_track; and not %red_track; and not %green_track; and %blue_track;</Filter>">
<!ENTITY yellow_red_hiking_filter "<Filter>%yellow_track; and %red_track; and not %green_track; and not %blue_track;</Filter>">
<!ENTITY yellow_green_hiking_filter "<Filter>%yellow_track; and not %red_track; and %green_track; and not %blue_track;</Filter>">
<!ENTITY yellow_blue_hiking_filter "<Filter>%yellow_track; and not %red_track; and not %green_track; and %blue_track;</Filter>">
<!ENTITY red_green_hiking_filter "<Filter>not %yellow_track; and %red_track; and %green_track; and not %blue_track;</Filter>">
<!ENTITY red_blue_hiking_filter "<Filter>not %yellow_track; and %red_track; and not %green_track; and %blue_track;</Filter>">
<!ENTITY green_blue_hiking_filter "<Filter>not %yellow_track; and not %red_track; and %green_track; and %blue_track;</Filter>">
<!ENTITY red_green_blue_hiking_filter "<Filter>not %yellow_track; and %red_track; and %green_track; and %blue_track;</Filter>">
<!ENTITY yellow_green_blue_hiking_filter "<Filter>%yellow_track; and not %red_track; and %green_track; and %blue_track;</Filter>">
<!ENTITY yellow_red_blue_hiking_filter "<Filter>%yellow_track; and %red_track; and not %green_track; and %blue_track;</Filter>">
<!ENTITY yellow_red_green_hiking_filter "<Filter>%yellow_track; and %red_track; and %green_track; and not %blue_track;</Filter>">
<!ENTITY yellow_red_green_blue_hiking_filter "<Filter>%yellow_track; and %red_track; and %green_track; and %blue_track;</Filter>">
